### ISSUE TITLE
could not reproduce 4iiy example run

### ISSUE THREAD

**Issue by aksangha** [HaotianZhangAI4Science/ResGen#2]
Hi 
I tried to run the example that came with code but gen.py script stopped giving following error after successfully generating the conformers.

----------
successfully generate: O=C1OCCc2cc(O)c(O)cc21
successfully generate: Cn1c(=O)[nH]c2ncccc2c1=O
Traceback (most recent call last):
  File "/storage/progs/ResGen/gen.py", line 232, in <module>
    prob = logp_to_rank_prob(np.array([p.average_logp[2:] for p in queue_tmp]),)  # (logp_focal, logpdf_pos), logp_element, logp_hasatom, logp_bond
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3176,) + inhomogeneous part.

--------------------------------------

Removing extra comma did not help either 

Traceback (most recent call last):
  File "/storage/progs/ResGen/gen.py", line 232, in <module>
    prob = logp_to_rank_prob(np.array([p.average_logp[2:] for p in queue_tmp]))  # (logp_focal, logpdf_pos), logp_element, logp_hasatom, logp_bond
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5942,) + inhomogeneous part

**Comment by HaotianZhangAI4Science** [comment]
Sorry to respond late, I have yet to encounter this issue you've descriped. Have you there been other instances where you've sucessfully tested? I'm currently uploading additional examples for your perusal. Furthermore, I will attempt to replicate the problem you're experiencing in order to  help solve it. Could you please provide a list of your environments? 
![image](https://github.com/HaotianZhangAI4Science/ResGen/assets/106578915/0dd93930-8b25-473c-ab37-82c5c7240e8e)
 This is my results, code is directly downloaded from the Git.

**Comment by HaotianZhangAI4Science** [comment]
I found the possible reason, now please download the updated version of resgen. The main changes are in gen.py and utils.sample.py. Thanks for reporting this bug!
